[package]
name = "fakeyou"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
reqwest = {version = "0.11", features = ["cookies", "json"]}
serde = {version="1.0", features= ["derive"]}
serde_json = "1.0"
thiserror = "1.0.40"
uuid = {version = "1.4.1", features=["v4", "fast-rng"] }